### ISSUE TITLE
DB model changes to support faster sync and multiple strategies

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-server#365]
DB diagram: https://dbdiagram.io/d/6228ad1661d06e6eadcf53d1

**Tasks**
- Migration to add new columns and indexes as per the above link.
- Changing all the Tx sync queries to the native queries that will be constructed dynamically based on the subject_type configuration.

**Comment by vinayvenu** [comment]
In the migration, we will need to consider performance of migration as well. Updating table with values will be slow because of triggers and indexes. We will need to disable them before running the update query. 
It might help doing this in batches of 10,000 or so. This means writing a function to do the migration and calling it.

**Comment by vindeolal** [comment]
sync_settings jsonb inthe user table should be `{"subjectIds": [], "syncConcept1Values": [], "syncConcept2Values":[]}`.
Admin UI for the user assignment is not done in this release.
