### ISSUE TITLE
Google drive file urls cannot be uploaded through csv upload

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#496]
https://avni.freshdesk.com/a/tickets/2290

**Comment by petmongrels** [comment]
The direct link provided by Google Drive now returns an HTML page, hence apart from the extension the file download is also broken due to this.
We can suggest people use this site - https://sites.google.com/site/gdocs2direct/?pli=1

This provides a direct link that downloads the file and gets the correct extension. The steps are documented here now - https://avni.readme.io/docs/structure-import-metadata-excel-excel#google-drive-files
