### ISSUE TITLE
(Analysis) Fix duplicate syncs

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#511]
https://avni.freshdesk.com/a/tickets/2450

Duplicate rows have been deleted as part of https://github.com/avniproject/rejuvenating-waterbodies/blob/main/data%20migrations/FD2450.sql

This card is to identify the root cause and fix it. 

Reopened this issue since similar issues have arised: https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/945 and we need to find the reason behind duplicate syncs.

- Fixing duplicate syncs is necessary so that user doesn't face error because of failing unique constraint, and the performance of the app doesn't get affected.
- From bugsnag can identify how frequently the duplicate syncs happen.

**Comment by 1t5j0y** [comment]
[File with duplicate rows that were deleted.](https://app.zenhub.com/files/64591222/f9ef4b41-1065-44c0-8b8c-64b036f7f66b/download)  Rename to .csv.
3 outlier records from 2021 and 2022. Most duplicate records are since Jan 10.
Found some co-relation of occurrences of duplicates during complete syncs after previous incomplete syncs but this is not true for all cases.
Found multiple records in sync_telemetry with the same start time for the same user for all sync_sources (manual, automatic and automatic-upload-only) but this has been occurring previously (before Jan 10) as well.
Records have definitely come in via duplicate POST calls from the client (checked server logs).
In sync_telemetry, for these cases, can see records with entity_status for push records with `done` count as double of `todo`.

**Comment by vinayvenu** [comment]
1. Verify if there are unique constraint violations for other tables during sync.

**Comment by 1t5j0y** [comment]
Found for program_encounter
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/63c1eccf5002d9000a00379e?filters[event.since]=30d&filters[error.status]=open

org.springframework.dao.DataIntegrityViolationExceptionQueryExecutorImpl.java:2270
could not execute statement; SQL [n/a]; constraint [program_encounter_uuid_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by mahalakshme** [comment]
Reopened this issue since similar issues have arised: https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/945 and we need to find the reason behind duplicate syncs.

**Comment by vinayvenu** [comment]
@mahalakshme since you already have an issue to handle duplicates, and this ticket is about group_subject, not eligibility, is it required to keep this ticket open?

**Comment by vinayvenu** [comment]
Adding to list of issues in background sync - https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/953
