### ISSUE TITLE
Fix ETL issue

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#525]
Since we had an incident on April 6 where we had multiple instances of avni-etl running, we have stopped ETL on production. 

We are currently not sure if the data is in a consistent state, and the best way to handle this is to recreate all ETL schemas. 

### Tasks
- Recreate ETL for all important ETL schemas
- Use flock to ensure existing cron jobs do not step on each other

**Comment by himeshr** [comment]
Made change to start.sh to prevent running more than one etl job at a given point of time:

[openchs@ip-10-100-1-238 avni-etl]$ cat ./start.sh
#!/bin/bash

if [ ! -e /opt/avni-etl/etl.flg ]; then
	touch /opt/avni-etl/etl.flg;
	printf 'ETL Job Starting, at %s\n' "$(date)" >> /opt/avni-etl/log/etl-trigger.log
	OPENCHS_DATABASE_URL="jdbc:postgresql://serverdb.openchs.org.:5432/openchs" nohup java -Dlogging.file=/opt/avni-etl/log/avni.log -Dlogging.path=/opt/avni-etl/log/ -Dlogging.file.max-size=5mb -Xmx250m -XX:ErrorFile=/opt/avni-etl/log/jvm.log -jar /opt/avni-etl/avni-etl.jar $1 >> /opt/avni-etl/log/etl.log 2>&1;
	rm /opt/avni-etl/etl.flg;
	printf 'ETL Job ended, at %s\n' "$(date)" >> /opt/avni-etl/log/etl-trigger.log
else
	printf 'ETL Job already in-prorgess, Not triggering it again. %s\n' "$(date)" >> /opt/avni-etl/log/etl-trigger.log
fi

**Comment by himeshr** [comment]
Completed ETL Schema-drop and re-create for following organisations on PROD:
rsv,shelter,rise,jsscp,ihmp,jnpct,chetna_sneha,yenepoya,sssma,lahi,saahas,stccv,jscs,sncu,sakhiapp,rwbniti,muktipath,ad,adsr,lfeteach,hasiru_karnataka,apfodisha,iph_ctrith,rahi,power,rwb2023,rwb

Failed only for 2 orgs due to data issue: jnpct and power

[https://app.zenhub.com/files/64591222/85f12b5d-8e5b-4ad8-803b-40b559483d1e/download](https://app.zenhub.com/files/64591222/85f12b5d-8e5b-4ad8-803b-40b559483d1e/download)
