### ISSUE TITLE
When syncing voided program enrolment/program encounter/encounter, not searching for voided form mapping

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#544]
### Acceptance criteria
- When there is no non-voided form mapping found during sync, order and pick the latest voided form mapping
- Do the above this for program enrolment, encounter and program encounter

### Testing
- See below for methods to reproduce the issue
- It is assumed that this problem will remain in cases where encounter types are shared across subject types, and if these subject types have different lowest_address_levels, we will have inconsistent syncs happening. Do not test this scenario

#### **Steps to reproduce:**
- Create a program, form mapping
- Enrol subjects to the program
- Void the program
- Clear app data
- sync
- can see the issue as shown in the image below.

#### **Code analysis:**
In ProgramEnrolmentController, getProgramEnrolmentsByOperatingIndividualScope method's we are not finding for voided form mappings in formMappingService.find function. This needs to be fixed since we need to sync voided program enrolments so that we dont show the voided data in the user app.

#### **Significance of fixing it apart from the usecase mentioned:**
- These kind of issues slows down implementation team work
- The issue occurred when solving the ticket: https://avni.freshdesk.com/a/tickets/2576. Fixing this will help in resolving the ticket faster or prevent tickets with above issue occurring. As a woraround, the form-mapping was unvoided to fix the ticket.

#### **Screenshot:**

- ![Screenshot 2023-04-21 at 7.37.08 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/64951292-6111-41b4-b082-ce24e0b8154d)

- For program encounter: with loginid: taqi@iph_ctrith, env: prod
![WhatsApp Image 2023-05-02 at 22.04.14.jpg](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/d5be2414-8a44-4661-8033-b120ec15fbde)

**Comment by vinayvenu** [comment]
@mahalakshme non-existent form mappings for a program enrolment is an incorrect data situation. We cannot look at voided form mappings because there could be multiple, and we cannot assume which one is correct.

**Comment by mahalakshme** [comment]
when deleting a form we would probably be voiding the form mapping also. there is 13948 voided form mappings in prod db. When checking for unvoided form mappings we get by program and do findFirst - we can do the same for this as well.

**Comment by mahalakshme** [comment]
the above issue has happened for encounters as well

**Comment by vinayvenu** [comment]
Form mappings are voided whenever we delete a subject type, program or encounter type. 

However, voided subject types, programs and encounter types, as well as their transactional data are synced to the client. 

When syncing, we need to find the sync scope (catchment, direct assignment etc) of an encounter. This requires us to look up the form mapping, find the subject type and then look up the sync scope from it. We need a non-voided form mapping in order to do this. 

If we ever delete an existing program or encounter type, the client still expects sync to happen, and we try to look up form mappings. If these are unavailable, then the sync fails because it is hard to figure out the subject type that the form mapping is associated to. 

Solution options
1. Do not void form mappings even when the original entity is voided
2. Look up the form mapping with highest last_modified_date_time if no unvoided form mapping available

I am not sure of the impact of 1 on other parts of the application.
