### ISSUE TITLE
Sync attribute inconsistencies

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#545]
Analyse and fix issues found here

https://reporting.avniproject.org/question/2114-sync-attributes-inconsistencies

**Comment by himeshr** [comment]
## Update the sync_concept_1_value using following commands: 
 - 
update individual set observations = observations || '{"be0ab05f-b0f3-43ec-b598-fdde0679104a": "a77bd700-1409-4d52-93bc-9fe32c0e169b"}' ::jsonb  where id in (
    1300970,
    1304824,
    1321013,
    1321124
    );
 - 
update program_encounter  set sync_concept_1_value = '8ebbf088-f292-483e-9084-7de919ce67b7'
where sync_concept_1_value = '[8ebbf088-f292-483e-9084-7de919ce67b7]' and organisation_id = 242;

 - 
update program_enrolment  set sync_concept_1_value = '8ebbf088-f292-483e-9084-7de919ce67b7'
where sync_concept_1_value = '[8ebbf088-f292-483e-9084-7de919ce67b7]' and organisation_id = 242;

**Comment by himeshr** [comment]
The issues reported from "sync attribute inconsistencies" were all due to mismatch in syncConcept1Value which had a StringArray value  instead of a single String.

This anamoly was caused due to issue reported as part of https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/509, which has already been fixed.

Hence no additional code changes will be done to fix this issue.
