### ISSUE TITLE
Duplicate subject migration entries created in the server

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#617]
About 30% of subject migration entries in the subject_migration table are duplicates. Every subject migration is creating duplicate rows in the subject migration table. 

Remove code in IndividualController that creates the duplicate entries

Removal of data is part of https://github.com/avniproject/avni-server/issues/618

**Comment by mahalakshme** [comment]
@vinayvenu 2 questions:

1. I am unable to find where we are making the other call to markSubjectMigrationIfRequired. You think it will get synced when the /subjectMigrations sync happen. If so, I think we cant remove it here, since createIndividual method is common for saveForWeb in IndividualController as well. 

2. I see we are removing updating of decisions? Where else we are doing it that we have removed it here?

**Comment by vinayvenu** [comment]
The piece removed is duplicated in ```createIndividual``` method.
