### ISSUE TITLE
Check the performance gain after caching

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#643]
### Acceptance criteria:
- Since now that 5.0.4 release is out, analyse the performance gains after the implementation of L2 caching: https://github.com/avniproject/avni-server/issues/608
- Also identify if the release has had any downside effects on performance

### Why
This will help us to plan our future stories accordingly

**Comment by 1t5j0y** [comment]
Caching seems to have achieved the desired results.

Number of critical events has gone down significantly since Oct 18 (prior to 5.0.1 release - not sure if some other indexing/optimisation was done on this day).
user, concept, concept_answer selection have dropped off the list of time consuming db operations.
Previous throughput is satisfied with lesser DB load.
App server CPU and memory utilisation do not seem to be affected.
Transactions are returning quicker and Apdex score is higher.
