### ISSUE TITLE
Avni external API providing date time for date fields

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#671]
Avni stores date observations as datetime in the database. Fixing this is a larger change.

But Avni external API also exposes the observation data as date time value. External systems that accept date do not expect date to be represented as date time. So they trim the time part of take the date value. This becomes one day old value. This problem is present in bahmni and goonj integration.

Avni API should present the date as describe in standards as "YYYY-MM-DD"
- https://jsonapi.org/recommendations/#date-and-time-fields
- https://www.w3.org/TR/NOTE-datetime

Goonj code which transforms datetime to date can/should be removed.

This fix is bit urgent for Ashwini, so marking it in release 7.

**Comment by vinayvenu** [comment]
### Testing notes
Here are the changes made for this story

1. Introducing a request parameter called version. This can be used by all api requests
2. Change to the mechanism of retrieving date observations so that for version 1, it will provide dates of the form ```2000-10-31T18:30:00.000+00:00``` and for version 2, it will be ```2000-10-31```
3. Any version other than 1 or 2 will throw an error
4. Refactoring of the mechanism of retrieving observations to reduce unnecessary db calls

In order to test, other than the version changes mentioned above, the following regression is required
1. Get of subject with different kind of observations (including dates)
2. Special care to be given for group and repeatable group observations


Making Goonj code change out of scope for this change. Will follow up with a new card once this is settled.

**Comment by himeshr** [comment]
#Testing notes

--------
--------

## Get specific Subject API

Request:
--------

Get Subject API call invoked for distribution with "ID": "6e914409-97fc-4e5d-ad63-7a9d1b9e42c3",

Received response:
------------------

for version 1 and null => "Distribution Date": "2023-10-17T18:30:00.000Z",
for version 2 and any other number => "Distribution Date": "2023-10-18",
for version value that is not an Integer => java.lang.NumberFormatException

--------
--------

## Get List of Subjects API with filters

Request:
--------

Get Subject API call invoked for Activities with date filters
```
lastModifiedDateTime:2023-10-01T00:00:00.001Z
size:5
page:0
subjectType:Activity
```

Received response:
------------------

for version 1 and null => For Activity "ID": "a2654431-f156-4780-aa48-e7c7d74ef888", "Activity Start Date": "2023-10-10T18:30:00.000Z",
for version 2 and any other number => For Activity "ID": "a2654431-f156-4780-aa48-e7c7d74ef888", "Activity Start Date": "2023-10-11",
for version value that is not an Integer => java.lang.NumberFormatException

--------
--------

## Get of Distribution with a Repeatable Question Group having a Date type concept also adheres the version param specified

Request:
--------

Get Subject API call invoked for distribution with "ID": "6e914409-97fc-4e5d-ad63-7a9d1b9e42c3", 

Received response:
------------------

for version 1 and null => within  "Inventory details" RepeatableQuestionGroup, "Activity Start Date": "2023-10-10T18:30:00.000Z" is returned
for version 2 and any other number => within  "Inventory details" RepeatableQuestionGroup, "Activity Start Date": "2023-10-11" is returned
for version value that is not an Integer => java.lang.NumberFormatException

--------
--------

**Comment by petmongrels** [comment]
Since this has been done using versioning. We can consider is not risky for releasing.
