### ISSUE TITLE
Issue when trying to fetch media

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#684]
### Issue:
https://avni.freshdesk.com/a/tickets/3475
![Image](https://github.com/avniproject/avni-server/assets/10369963/a01ee755-5dcc-49aa-9b59-9aa2eb858e42)

### Analysis:
The URL I think should ve been of the below format:
GET /media/signedUrl?url=https%3A%2F%2Fprod-user-media.s3.ap-south-1.amazonaws.com%2Fgarima%2Ficons%2Fba97b2a7-94a3-4569-8bf6-70ebed1f12b4.png but has only the image name as value. May be some env variable in prod config is missing or issue when constructing the url in the code.

**Comment by petmongrels** [comment]
@mahalakshme there are invalid observations in shelter individuals caused due to upload I think. this query can be run to see the list of such observations which do not have AWS unsigned url.

`select observations ->> 'f5791a8d-4513-42b0-9330-5bef2a56a176', last_modified_by_id, manual_update_history
from individual
where observations ->> 'f5791a8d-4513-42b0-9330-5bef2a56a176' is not null and observations ->> 'f5791a8d-4513-42b0-9330-5bef2a56a176' not like 'http%';`

**Comment by petmongrels** [comment]
The web app has been fixed to display a message when the media url is wrong and cannot be signed.

**Comment by petmongrels** [comment]
screenshot in the ticket
