### ISSUE TITLE
Last Modified User is not updating when updating Subject Summary Rule

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-server#700]
**Describe the bug**
Last Modified is not updating.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to subject check user and login with different user.
2. Click on edit
3. Click on save
4. Check the Last Modified

**Expected behaviour**
Modified should show who is modifying it.

https://github.com/avniproject/avni-webapp/assets/106894932/11739bd0-7078-44b0-94ba-d7d881a67558

**Comment by vinayvenu** [comment]
@vedfordev I can't seem to reproduce this issue. The video also doesn't work. Can you confirm if this issue still persists in staging?

**Comment by vedfordev** [comment]
@vinayvenu issue still exists. date is changing but username is not changing.

**Comment by vinayvenu** [comment]
@vedfordev thanks. We pick the lastModifiedDateTime from the higher value of SubjectType and OperationalSubjectType while we pick up lastModifiedBy directly from the OperationalSubjectType table. This becomes a problem when we don't make any change to the OperationalSubjectType table during an update. 

We should do a similar logic for lastModifiedBy as well.

**Comment by vedfordev** [comment]
@vinayvenu lastModifiedDateTime should be change automatically via jpa auditing feature. why we are doing manual update?

**Comment by vinayvenu** [comment]
lastModifiedDateTime will change automatically only for rows that have changes. In this scenario, there are changes only in the subject_type table, and not the operational_subject_type table. Audit is working as designed. 

When showing this on the screen, we show the lastModifiedDateTime of the greatest among the two dates - subjectType and operationalSubjectType. However, we don't do a similar thing for the lastModifiedBy field. Which is why you see the discrepancy.

**Comment by vedfordev** [comment]
@vinayvenu Can we can set here from subject_type rather than operational_subject_type?[Code](https://github.com/avniproject/avni-server/blob/bc00ddca2c4873c062d0c290fd0e00291c66d036/avni-server-api/src/main/java/org/avni/server/web/request/webapp/SubjectTypeContractWeb.java#L69) same for date as well

**Comment by vinayvenu** [comment]
@vedfordev 
1. The same issue seems to happen across multiple operational entities (OperationalEncounterType, OperationalProgram etc). It might be best to fix all of these instead of just the SubjectType
2. One way to do this is to pull up the comparison functionality to Auditable. We already have duplication across two methods in the same class. if you do this, ensure that the method is marked @JsonIgnore so it doesn't affect API responses
3. Try writing a simple test so we don't have to guess when reviewing code

**Comment by vedfordev** [comment]
@vinayvenu done with above task.

1. added method in **getLastModified** in **OrganisationAwareEntity** because if we put in Auditable interface we are comparing it in interface method. it calls leads to infinite calls. because we are comparing via getLastModifiedDateTime when Operational<item> called it's method  getLastModifiedDateTime.
