### ISSUE TITLE
Custom standard report card execution compatibility with older client versions

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-server#781]
As part of avniproject/avni-webapp#1263, standard card type names were changed from 'Last 24 hours..' to 'Recent..'.

This breaks custom standard report cards on older client versions which uses the old standard report card type name (set in avni-models) to determine the function to be called to calculate the value for the report card.

### AC:
- Make the change backward compatible while retaining the new standard card type name in the webapp.

**Comment by himeshr** [comment]
## Scenario of concern
During code review, came up with following scenario based on our last week's discussion regarding Custom Dashbpard Filters sync to older verisons of the client:
- Create new Custom Dashboard Report card of Standard Recent type, with Duration string of say 3 days
- User on old client version will sync and receive this card it would ignore the durationString, but it would work as though it is a simple 24 hours Report card instead of 3 days 
- Later when the User upgardes to a newer version of the client, we'll continue to see it working as a 24 hours Report card, as the duration info was already lost

### Suggestions 
To recover from this kind of error scenario, one of the suggestions is to reset sync for only the ReportCard row in the EntitySyncStatus Realm DB table.
<img width="1430" alt="Screenshot 2024-09-09 at 12 32 11 PM" src="https://github.com/user-attachments/assets/d0849c68-fd78-4602-af18-54a0a078486f">

**Comment by himeshr** [comment]
> ## Scenario of concern
> During code review, came up with following scenario based on our last week's discussion regarding Custom Dashbpard Filters sync to older verisons of the client:
> 
> * Create new Custom Dashboard Report card of Standard Recent type, with Duration string of say 3 days
> * User on old client version will sync and receive this card it would ignore the durationString, but it would work as though it is a simple 24 hours Report card instead of 3 days
> * Later when the User upgardes to a newer version of the client, we'll continue to see it working as a 24 hours Report card, as the duration info was already lost


Based on group discussion, it was concluded that we would be handling this via Versioned API support on server being done for following entity types in #782 : reportcard, dashboardfilter, dashboard, dashboardsection, sectioncardmapping, standardreportcardtype

**Comment by 1t5j0y** [comment]
### Testing
- Standard reports should work fine in 9.x apk and 10.x apk
- While configuring 'recent' type cards on webapp admin, it should still show 'recent' and not 'last 24'

**Comment by mahalakshme** [comment]
@1t5j0y whatever name we specify for 'Recent' type cards will show right?

**Comment by AchalaBelokar** [comment]
- [ ] downloaded 9.4 apk try to login with maha@apfodisha_dev it is showing me fast sync failed unknownServerErrorReason and after that I am trying to do slow syn it is going on login page 
I am using this apk https://app.circleci.com/pipelines/github/avniproject/avni-client/2648/workflows/49e915d2-5916-49af-9463-53aa218190ae/jobs/17103/artifacts
unknownServerErrorReason. Http 406. 
at ServerError (address at index.android.bundle:1:1326035)
at processResponse (address at index.android.bundle:1:1323267)
at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2k3l5153/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2k3l5153/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply ((native)::)
at anonymous (address at index.android.bundle:1:246985)
at _callTimer (address at index.android.bundle:1:245979)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:246144)
at callReactNativeMicrotasks (address at index.android.bundle:1:248055)
at __callReactNativeMicrotasks (address at index.android.bundle:1:97211)
at anonymous (address at index.android.bundle:1:96350)
at __guard (address at index.android.bundle:1:97088)
at flushedQueue (address at index.android.bundle:1:96261)
at callFunctionReturnFlushedQueue (address at index.android.bundle:1:96117)

**Comment by mahalakshme** [comment]
Add documentation for workaround explaining the case in readme - under Implementors guide
