### ISSUE TITLE
Some bundle uploads without change can still update report cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#804]
### AC:
```
select organisation_id, standard_report_card_input from report_card where standard_report_card_type_id
                                    not in (5,4,9,6,7,8);
```
- On doing the above we find that, unexpected standard report cards/non-standard report cards already have incorrect standard_report_card_input which needs to be reset to {}. And one of the organisation is prod organisation. Better to fix for all.
- The report card in prod org is not used in any dashboard, but still it will cause sync issue. Hence need to fix.
- Just add a query -> code review -> we can run on prod org.
- 
- 
### Testing:
- On creation of new org, 'Due Checklist' standard report card, should not get created. And creation of default dashboard with default standard report cards need to work
- Same as above on migration of an org from old MyDashboard to new custom default dashboard using the API.

**Comment by himeshr** [comment]
### SQL Query to list info regarding non-input type report-cards with non-empty value for 'standard_report_card_input'
```sql 
reset role;
SELECT o.name,
       oc.name,
       u.username,
       u.username,
       rc.created_date_time,
       rc.last_modified_date_time,
       srct.type
       standard_report_card_input
from report_card rc
         join standard_report_card_type srct on rc.standard_report_card_type_id = srct.id
         join organisation o on rc.organisation_id = o.id
         join organisation_category oc on oc.id = o.category_id
         join users u on rc.created_by_id = u.id
         join users u2 on rc.last_modified_by_id = u2.id
WHERE standard_report_card_type_id not in (5, 4, 9, 6, 7, 8)
  AND standard_report_card_input <> '{}';
  ```
  
 #### Output
  
<img width="1452" alt="Screenshot 2024-10-11 at 11 59 04 AM" src="https://github.com/user-attachments/assets/87162b79-f734-4933-a192-ae9c25bc107d">

### Analysis

The issue seems to have occurred only for "Due Checklist" type report cards which get auto generated as part of creation of Default CustomDashboard along with the other "StandardReportCardInput" type reportCards.

<img width="1111" alt="Screenshot 2024-10-11 at 12 00 56 PM" src="https://github.com/user-attachments/assets/debf894d-c019-437a-8517-c824cc9f855a">

### Code fix

We'll add appropriate check in code related to creation of Defautl custom dashboard to prevent this for future new organisation creation

https://github.com/avniproject/avni-server/commit/b90150622f4a9fbe4b79cb380bf0681be9de7235


### Data fix

We'll update the standard_report_card_input to '{}' for those reportCards of type DueChecklist with lastModifiedDateTime set to appropriate value.

https://github.com/avniproject/data-fixes/blob/main/all/dueChecklistStfRCInputReset.sql

**Comment by mahalakshme** [comment]
@himeshr But why is due checklist even got created? It is not part of the default dashboard also, by default. I think fix should be at that level. So moving to Code Review with comments. I can create separate card for this if there are concerns.

**Comment by mahalakshme** [comment]
@himeshr 
Default MyDashboard does not have DueChecklist report card. So this standard report card need not be created.

As of 9.3.0, only when 'showDueChecklistOnDashboard' is set in MyDashboard, we show duechecklist card on home dashboard. Currently no org is using this. And going forward, since everything will be a custom dashboard, including default dashboard, it can be added when needed.

I can make this a separate card, if any concerns.
